<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <?php if($this->messages) : ?>
            <?php if($this->auth) : ?>
                <div class="alert alert-success" role="alert">
                    <b>Well done!</b> <?php echo $this->messages; ?>
                </div>
            <?php else : ?>
                <div class="alert alert-danger" role="alert">
                    <b>Oh snap!</b> <?php echo $this->messages; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<?php $form = $this->form; ?>
        <?php $form->setAttribute('action', $this->url('home')); ?>
		<?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>

        	<?php echo $this->formhidden($form->get('csrf')); ?>

        	<!-- username field -->
        	<div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('username')); ?>
                    </div>
                </div>
            </div>

            <!-- password field -->
        	<div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('password')); ?>
                    </div>
                </div>
            </div>

            <!-- submit -->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <?php  echo $this->formsubmit($form->get('submit')); ?>
                </div>
            </div>

        <?php echo $this->form()->closeTag(); ?>
	</div>
</div>